# Numpy

In [ ]:
# Numpy --> Num Py

In [ ]:
import numpy

In [ ]:
numpy.array([12,12])

array([12, 12])

In [1]:
import numpy as np

In [ ]:
np.array([12,12])

array([12, 12])

In [ ]:
type(np.array([12,12]))

numpy.ndarray

In [ ]:
a = np.array([2,7,9,4])

In [ ]:
type(a)

numpy.ndarray

In [ ]:
a.ndim

1

In [ ]:
a = np.array([[2,7,9,4],[3,8,6,9]])
a.ndim

2

In [ ]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
np.arange(5,32,2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31])

In [ ]:
for i in range(10):
  print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
np.zeros(12)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.ones(12)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.ones(10)*15

array([15., 15., 15., 15., 15., 15., 15., 15., 15., 15.])

In [ ]:
a = np.array([12,76,9,54,78.98,'Hari'])

In [ ]:
a

array(['12', '76', '9', '54', '78.98', 'Hari'], dtype='<U32')

In [ ]:
a[2]

'9'

In [ ]:
type(a[2])

numpy.str_

In [ ]:
a[2:4]

array(['9', '54'], dtype='<U32')

In [ ]:
a[-3]

'54'

In [ ]:
a[-3:-1]

array(['54', '78.98'], dtype='<U32')

In [ ]:
a[-3] = 'AI'

In [ ]:
a

array(['12', '76', '9', 'AI', '78.98', 'Hari'], dtype='<U32')

In [ ]:
# Argmax, argmin


a = np.array([12,5,123])
a

array([ 12,   5, 123])

In [ ]:
a.min()

5

In [ ]:
a.max()

123

In [ ]:
a.argmin()

1

In [ ]:
a.argmax()

2

In [ ]:
demo = np.array([[1,2,3,4],[4,3,2,1]])
demo

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

In [ ]:
demo.ndim

2

In [ ]:
demo.shape

(2, 4)

In [ ]:
demo.reshape(4,2)

array([[1, 2],
       [3, 4],
       [4, 3],
       [2, 1]])

In [ ]:
d1 = np.expand_dims(demo,1)

In [ ]:
d1.ndim

3

In [ ]:
d2 = np.expand_dims(demo,0)

In [ ]:
d2.ndim

3

In [ ]:
np.random.rand(5,5)

array([[0.6547236 , 0.99035747, 0.76450061, 0.99438162, 0.52269966],
       [0.93286235, 0.964282  , 0.34405783, 0.31487077, 0.03269231],
       [0.99173396, 0.6412015 , 0.61046258, 0.91640446, 0.63298564],
       [0.65119684, 0.74664752, 0.66180139, 0.44663054, 0.15343605],
       [0.29044515, 0.84176884, 0.76027005, 0.93542389, 0.43695852]])

In [ ]:
np.random.randint(2,7)

6

In [ ]:
sq = np.random.randint(2,20,3)
sq

array([10,  7, 10])

In [ ]:
np.log(sq)

array([2.30258509, 1.94591015, 2.30258509])

In [ ]:
np.sqrt(sq)

array([3.16227766, 2.64575131, 3.16227766])

# Pandas

In [2]:
import pandas as pd

In [3]:
# Pandas  ---   1) Series 2) Dataframe

In [4]:
# Series

series = pd.Series([1,2,3,4,7])
series

0    1
1    2
2    3
3    4
4    7
dtype: int64

In [7]:
series2 = pd.Series(np.random.rand(13))
series2

0     0.929962
1     0.911854
2     0.512208
3     0.702489
4     0.185854
5     0.523886
6     0.920421
7     0.959655
8     0.266016
9     0.986232
10    0.235598
11    0.739072
12    0.888657
dtype: float64

In [8]:
series2[10]

0.23559757643689172

In [9]:
series2[10] = 1.234567

In [10]:
series2

0     0.929962
1     0.911854
2     0.512208
3     0.702489
4     0.185854
5     0.523886
6     0.920421
7     0.959655
8     0.266016
9     0.986232
10    1.234567
11    0.739072
12    0.888657
dtype: float64

In [11]:
series2[2:10]

2    0.512208
3    0.702489
4    0.185854
5    0.523886
6    0.920421
7    0.959655
8    0.266016
9    0.986232
dtype: float64

In [12]:
index = ['a','b','c','d','e','f','g','h','i','j','k','l','m']
index

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm']

In [13]:
len(index)

13

In [14]:
series2.index = index

In [15]:
series2

a    0.929962
b    0.911854
c    0.512208
d    0.702489
e    0.185854
f    0.523886
g    0.920421
h    0.959655
i    0.266016
j    0.986232
k    1.234567
l    0.739072
m    0.888657
dtype: float64

In [16]:
series2[4]

0.18585360885676938

In [17]:
series2['e']

0.18585360885676938

In [18]:
s1 = pd.Series(np.random.rand(5))
s1

0    0.305397
1    0.375113
2    0.349465
3    0.643453
4    0.642866
dtype: float64

In [19]:
s2 = s1
s2

0    0.305397
1    0.375113
2    0.349465
3    0.643453
4    0.642866
dtype: float64

In [24]:
s1[2]=1111.345

In [25]:
s1

0       0.305397
1       0.375113
2    1111.345000
3       0.643453
4       0.642866
dtype: float64

In [22]:
s2

0       0.305397
1       0.375113
2    2023.000000
3       0.643453
4       0.642866
dtype: float64

In [23]:
s3 = s1.copy()
s3

0       0.305397
1       0.375113
2    2023.000000
3       0.643453
4       0.642866
dtype: float64

In [26]:
s3

0       0.305397
1       0.375113
2    2023.000000
3       0.643453
4       0.642866
dtype: float64

In [28]:
subject = ['Maths','Science','Social','English']
marks = [78, 89, 79, 86]

In [29]:
pd.Series(marks,subject)

Maths      78
Science    89
Social     79
English    86
dtype: int64

In [34]:
# DataFrame

dummy = pd.DataFrame([s1,s3,s2])
dummy

0         1         2         3         4
0  0.305397  0.375113  1111.345  0.643453  0.642866
1  0.305397  0.375113  2023.000  0.643453  0.642866
2  0.305397  0.375113  1111.345  0.643453  0.642866

In [32]:
index = ['a','b','c']
column = ['a','b','c','d','e']

In [33]:
print(index)
print(column)

['a', 'b', 'c']
['a', 'b', 'c', 'd', 'e']


In [35]:
dummy.columns = column
dummy.index = index

In [36]:
dummy

a         b         c         d         e
a  0.305397  0.375113  1111.345  0.643453  0.642866
b  0.305397  0.375113  2023.000  0.643453  0.642866
c  0.305397  0.375113  1111.345  0.643453  0.642866

In [37]:
d = {'Name':['Hari','Srikanth','Saumya'],
     'Age':[29,32,39],
     'Gender':['M','M','F'],
     'Technology': ['AI', 'DA', 'ML']}

d

{'Name': ['Hari', 'Srikanth', 'Saumya'],
 'Age': [29, 32, 39],
 'Gender': ['M', 'M', 'F'],
 'Technology': ['AI', 'DA', 'ML']}

In [38]:
data = pd.DataFrame(d)
data

Name  Age Gender Technology
0      Hari   29      M         AI
1  Srikanth   32      M         DA
2    Saumya   39      F         ML

In [39]:
data['Technology']

0    AI
1    DA
2    ML
Name: Technology, dtype: object

In [40]:
data['Salary (LPA)'] = [9.2, 12.7, 15.4]

In [41]:
data

Name  Age Gender Technology  Salary (LPA)
0      Hari   29      M         AI           9.2
1  Srikanth   32      M         DA          12.7
2    Saumya   39      F         ML          15.4

In [44]:
data.drop('Salary (LPA)',axis=1,inplace=True)

In [45]:
data

Name  Age Gender Technology
0      Hari   29      M         AI
1  Srikanth   32      M         DA
2    Saumya   39      F         ML

In [49]:
data.loc[3] = ['Mahi',55,'M','CAD']

In [50]:
data

Name  Age Gender Technology
0      Hari   29      M         AI
1  Srikanth   32      M         DA
2    Saumya   39      F         ML
3      Mahi   55      M        CAD

In [52]:
data = data.drop(3,axis=0)

In [53]:
data

Name  Age Gender Technology
0      Hari   29      M         AI
1  Srikanth   32      M         DA
2    Saumya   39      F         ML

In [ ]:
# Syntax
# ----> loc[row starting name:row ending name,column starting name:column ending name]
# ----> iloc[row starting index:row ending index,column starting index:column ending index]

In [55]:
data.loc[0:1,'Name':'Gender']

Name  Age Gender
0      Hari   29      M
1  Srikanth   32      M

In [56]:
data.iloc[0:2,0:3]

Name  Age Gender
0      Hari   29      M
1  Srikanth   32      M

In [57]:
# info

data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Name        3 non-null      object
 1   Age         3 non-null      int64 
 2   Gender      3 non-null      object
 3   Technology  3 non-null      object
dtypes: int64(1), object(3)
memory usage: 228.0+ bytes


In [59]:
data.describe(include='all')

Name        Age Gender Technology
count      3   3.000000      3          3
unique     3        NaN      2          3
top     Hari        NaN      M         AI
freq       1        NaN      2          1
mean     NaN  33.333333    NaN        NaN
std      NaN   5.131601    NaN        NaN
min      NaN  29.000000    NaN        NaN
25%      NaN  30.500000    NaN        NaN
50%      NaN  32.000000    NaN        NaN
75%      NaN  35.500000    NaN        NaN
max      NaN  39.000000    NaN        NaN

In [60]:
data['Gender'].value_counts()

M    2
F    1
Name: Gender, dtype: int64

In [61]:
data['Gender'].unique()

array(['M', 'F'], dtype=object)

In [62]:
data['Age'].mean()

33.333333333333336

In [63]:
data['Age'].median()

32.0

In [64]:
data['Technology'].mode()

0    AI
1    DA
2    ML
Name: Technology, dtype: object

In [65]:
max(data['Age'])

39

In [66]:
data['Age'].max()

39

In [67]:
data['Age'].min()

29